apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce
  labels:
    name: ecommerce
    environment: production
    project: ecommerce-marketplace
---
apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce-monitoring
  labels:
    name: ecommerce-monitoring
    environment: production
    project: ecommerce-marketplace
